### PR TITLE
chore: update k8s versions in version maps and default version

### PR DESCRIPTION
**Pull request by rohantmp**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix
/kind enhancement
/kind feature
/kind documentation
/kind test

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
part of ENG-4861

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster ...

**What else do we need to know?**

### CODE REVIEW

**Comment by rohantmp** [comment]
Working on the conformance tests too. Can add it to this PR if necessary

**Comment by FabianKramm** [comment]
@rohantmp you will need to update the templates as well as they currently have the version hardcoded

**Comment by rohantmp** [comment]
Apologies, meant to open this as draft for now

**Comment by rohantmp** [comment]
> you will need to update the templates as well as they currently have the version hardcoded

Ah, I see what you meant. Thanks :)

**Comment by rohantmp** [comment]
k0s has an out-of-band patch release k0s.1 Seeing if that works

**Comment by rohantmp** [comment]
k0s default version not being bumped as discussed since the latest version breaks

**Review by FabianKramm — APPROVED** [review]

**Pull request merged**
