### PR TITLE
add metrics server proxy docs

### PR DESCRIPTION
**Pull request by ishankhare07**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves ENG-1001 Docs - add documentation for metrics proxy

**Please provide a short message that should be published in the vcluster release notes**

**What else do we need to know?**

### CODE REVIEW

**Comment by matskiv** [comment]
I feel like the metrics proxy could be the recommended option. So rather than showing how the user should install metric-server, we should first suggest they try metrics-proxy. Wdyt @FabianKramm and @ishankhare07 ?

**Comment by ishankhare07** [comment]
I think you're refering to the section above this – which is more about installing metrics server inside vcluster – in that case yes I agree we can put this section above as a recommended option with an 'info' block saying it requires metrics server on the host cluster

**Comment by FabianKramm** [comment]
@matskiv yep I agree, we should recommend the user this feature if they want metrics inside vcluster

**Comment by matskiv** [comment]
@ishankhare07 yes, exactly!

**Review by matskiv — APPROVED** [review]
LGTM

**Pull request merged**
