### PR TITLE
Update translator.go

### PR DESCRIPTION
**Pull request by iamujjwalrawat**
hacktoberfest submission!

im from india!
request if you merge and label it hacktoberfest accepted it would be gracious.

### CODE REVIEW

**Review by FabianKramm — CHANGES_REQUESTED** [review]
@iamujjwalrawat thanks for the PR! Seems like while refactoring a lot of logic is missing now.

**Comment by rohantmp** [comment]
Hi @iamujjwalrawat , while submitting a pull request, please use the description and commit message to describe the desired outcome of the change. It is not clear as to the intentions of this PR, and there is no follow-up. I am closing this PR and labelling it according to the [Haktoberfest recommendations](https://hacktoberfest.com/participation/#spam)

**Comment by rohantmp** [comment]
Removed the label as I did go through the PR and see some good-faith changes. Apologies. I misread the PR at first.

**Comment by ThomasK33** [comment]
See comment on you're other PR: https://github.com/loft-sh/vcluster/pull/1315#issuecomment-1873962088

**Pull request closed without merging**
