### PR TITLE
Allow annotation of all objects created by the eks,8s and k0s charts

### LINKED ISSUE #714: Create globalAnnotations for eks, k8s and k0s
Thanks to @denniskorbginski and his PR #697 we can support `globalAnnotations` for all objects created by vcluster k3s. Would be nice if we add the same option to our other charts, so that the values stay consistent across the different charts.

### PR DESCRIPTION
**Pull request by Ab-hishek**
Signed-off-by: Ab-hishek <abhishek.agarwal1@nutanix.com>

**What issue type does this pull request address?**
/kind enhancement

**What does this pull request do? Which issues does it resolve?** 
resolves #714

**Please provide a short message that should be published in the vcluster release notes**
Added helm value "global.annotations" to eke, k8s and k0s charts that will add its annotations to all objects created in the chart. Annotations for specific objects have precedence over global ones.

**What else do we need to know?**

### CODE REVIEW

**Review by pratikjagrut — COMMENTED** [review]
Hey, @Ab-hishek Thank you for your PR. I noticed you'd missed a few objects to update. Following is the list, please add their charts too.

**eks chart**
- templates/api-deployment.yaml
- templates/api-service.yaml
- templates/controller-deployment.yaml
- templates/daemonset-hostpath-mapper.yaml
- templates/etcd-service.yaml
- templates/etcd-statefulset-service.yaml
- templates/etcd-statefulset.yaml
- templates/networkpolicy.yaml
- templates/pre-install-hook-job-role.yaml
- templates/pre-install-hook-job-rolebinding.yaml
- templates/pre-install-hook-job-serviceaccount.yaml
- templates/pre-install-hook-job.yaml
- templates/syncer-deployment.yaml

This is from eks charts please find other objects from other charts and add the annotation options there too.

**Review by pratikjagrut — CHANGES_REQUESTED** [review]
Please go through my first comment.

**Comment by Ab-hishek** [comment]
Sure. Will update accordingly.

**Comment by matskiv** [comment]
Hello @Ab-hishek 
Do you still plan to do the changes you discussed above, or should we close the PR and unassign you from the issue?

**Comment by Ab-hishek** [comment]
I currently do not have the cycles to work on these. You can unassign me.

**Comment by matskiv** [comment]
Thanks for the update. In that case I will close this PR.

**Pull request closed without merging**
