### PR TITLE
 Aliases for list/delete commands #389

### LINKED ISSUE #389: Aliases for list/delete commands
### Is your feature request related to a problem?

This request is not a problem. More of a convenience suggestion.

It would be nice to have the list/delete commands with the vcluster CLI have shorthand aliases (i.e. ls, rm). So I can run vcluster ls and vcluster rm as opposed to vcluster list and vcluster delete.

### Which solution do you suggest?

Using Cobra Aliases like [here](https://github.com/danielhelfand/vcluster/commit/0674e5439460188b44e565b645cee08b0091adac).

### Which alternative solutions exist?

I could alias the commands myself, but I hope these are pretty command shorthands for each subcommand that they would be familiar to most.

### Additional context

Depending on whether this is something that should be supported in the CLI, it might be useful to define standards around what aliases would be allowed moving forward.

### PR DESCRIPTION
**Pull request by Payback159**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #389 

**Please provide a short message that should be published in the vcluster release notes**
add aliases. `rm` for delete and `ls` for list.

**What else do we need to know?** 

I also briefly considered adding an alias for other commands. In all cases, however, one would have saved only 1 letter and there I thought, rather less aliases and for it a more comprehensible cli.

However, if anyone can think of a good alias for other commands, I'd be happy to add them.

### CODE REVIEW

**Comment by matskiv** [comment]
@Payback159 Thank you for submitting a PR! Would you mind changing `del` to `rm` as proposed in the original issue? It's a bit shorter, but mainly it won't interfere with CLI completion.

**Comment by Payback159** [comment]
Thank you @matskiv . Of course, the PR and also the short message for the release note are updated.

**Review by matskiv — APPROVED** [review]
Thank you for the PR @Payback159 !
LGTM and works as expected! :+1:

**Comment by matskiv** [comment]
Hello @Payback159  :wave: 
We are planning to bring some vcluster T-shirts to KubeCon Europe, and I want to set some aside for the contributors that will be present at the conference. Are you attending by any chance? :)

**Comment by Payback159** [comment]
Hi @matskiv, yes I will be there and would be very happy to receive a t-shirt. See you at KubeCon Europe! 👋

**Pull request merged**
