### PR TITLE
Make host rewrite image configurable

### PR DESCRIPTION
**Pull request by tamalsaha**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #
I need to be able to provide all the docker images used by vcluster from a private registry. This allows me to configure the rewrite hosts docker image.

**Please provide a short message that should be published in the vcluster release notes**
Make host rewrite image configurable in vcluster config

**What else do we need to know?**

### CODE REVIEW

**Comment by FabianKramm** [comment]
@tamalsaha thanks a lot for the PR! Whats the benefit over doing:
```
syncer:
  extraArgs:
  - --override-hosts-container-image="my-container-image"
```

**Comment by tamalsaha** [comment]
I am trying to use this as part of a cloud marketplace release where the image name/tag is auto injected from values file. I can't do that using the extraArgs. I need it to be a specific image key in the values file.

**Comment by FabianKramm** [comment]
@tamalsaha ah I see, is it possible to already use v0.20 for that as we changed the values.yaml structure there to be a lot more clear and there is a field like this at:
```
sync:
  toHost:
    pods:
      rewriteHosts:
        initContainer:
          image: "YOUR_IMAGE_HERE"
```

**Comment by tamalsaha** [comment]
That's great. I am waiting for 0.20 is come out. Until then, I am using 0.19.x

**Pull request closed without merging**
