### PR TITLE
upd eks images to 1-27-eks-11

### LINKED ISSUE #1206: add support for v1.27 on eks
### Is your feature request related to a problem?

vcluster-k3s and vcluster-k8s are already being set at 1.28, but vcluster-eks is still at 1.24.

### Which solution do you suggest?

upgrade vcluster-eks to 1.27 (which is coincidentally the most recent eks version)

### Which alternative solutions exist?

Manual patching the chart, but the current charts don't provide an easy way to change only the tag versions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joaocc**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #1206

**Please provide a short message that should be published in the vcluster release notes**
Updated vcluster-eks chart to 1.27-eks-11

### CODE REVIEW

**Review by neogopher — APPROVED** [review]
LGTM!!

**Comment by ThomasK33** [comment]
Thanks for the PR @joaocc 👍

**Comment by joaocc** [comment]
Thanks for the quick turnaround. Do you know which release will this be included in? Thx

**Comment by ThomasK33** [comment]
It’ll be part of 0.16, which will be released in the next week(s).

**Pull request merged**
