### PR TITLE
Adds min and max to LimitRange

### PR DESCRIPTION
**Pull request by emoreth**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
The LimitRange resource lacks options for `min` and `max`.

**Please provide a short message that should be published in the vcluster release notes**
Add min and max options to LimitRange

**What else do we need to know?**

### CODE REVIEW

**Comment by FabianKramm** [comment]
@emoreth thanks for creating this PR! With the current implementation this won't have any effect, are you sure this PR is complete since there are no chart changes.

**Comment by emoreth** [comment]
Sorry, I missed pushing a file 🤦

**Comment by FabianKramm** [comment]
@emoreth thanks for that, you will also need to add that to the `config.go` and then generate the schema via `go run hack/schema/main.go` as described in https://github.com/loft-sh/vcluster/tree/main/config . Then I can merge it

**Comment by emoreth** [comment]
I don't have a lot of experience in GO. I don't know why `go run hack/schema/main.go` removes `min` and `max` values from the `values.yaml` file, but I decided to include it anyway...

**Comment by emoreth** [comment]
@FabianKramm Sorry for the @, but this should be a quick one

**Review by FabianKramm — APPROVED** [review]
@emoreth thanks again! LGTM! Sorry for letting this hang so long

**Pull request merged**
