### PR TITLE
Fix statefulset broken tamplate

### LINKED ISSUE #122: Helm Chart: statefulset template, broken logic
[https://github.com/loft-sh/vcluster/blob/main/chart/templates/statefulset.yaml#L32](https://github.com/loft-sh/vcluster/blob/main/chart/templates/statefulset.yaml#L32)

spec.volumeClaimTemplates.0.spec.storageClassName by default renders as null instead of a value or empty string. This breaks kustomize validation.

```
  {{- if .Values.storage.persistence }}  <== default renders as to IF TRUE
  {{- if not .Values.storage.volumeClaimTemplates }}  <== defaults renders to IF NOT FALSE
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.storage.className }} <== undefined in values file
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  {{- else }}
  volumeClaimTemplates:
{{ toYaml .Values.volumeClaimTemplates | indent 4 }}
  {{- end }}
  {{- end }}
```

I'm actually surprised Helm doesn't complain about a null value to the key, seems like a break of yaml spec.

K8s doesn't care if the field is defined or not, and the docs simply state to use *a string*.
*storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set*
[https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1)
[https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#persistentvolumeclaimspec-v1-core](https://v1-21.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#persistentvolumeclaimspec-v1-core)

Proposed:

* Define the key 'storageClassName' only if a name is defined in values OR
* Define a default in values "Filesystem" is the inferred value when undefined per: [https://github.com/kubernetes/api/blob/release-1.21/core/v1/types.go#L489](https://github.com/kubernetes/api/blob/release-1.21/core/v1/types.go#L489)

### PR DESCRIPTION
**Pull request by hiteshwani29**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind enhancement

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #122 

**Please provide a short message that should be published in the vcluster release notes**
Fixed an issue where vcluster helm storageClass template is passing nil value to storageClassName field if className is not set/passed in the values.yaml

**What else do we need to know?**

### CODE REVIEW

**Review by FabianKramm — APPROVED** [review]

**Comment by FabianKramm** [comment]
@hiteshwani29 seems like your change causes all e2e tests to fail, would you mind to retake a look?

**Comment by hiteshwani29** [comment]
@FabianKramm Did changes to not set the storageClass at all. Can you relook at PR again?

**Comment by FabianKramm** [comment]
@hiteshwani29 thanks, LGTM!

**Comment by matskiv** [comment]
Hello @hiteshwani29 :wave: 
Thank you for the PR!
We are planning to bring some vcluster T-shirts to KubeCon Europe, and I want to set some aside for the contributors that will be present at the conference. Are you attending by any chance? :)

**Comment by hiteshwani29** [comment]
@matskiv will not be able to present at the kubeCon conference.

**Pull request merged**
