### PR TITLE
chore: Added table of content in README.md

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #

This pull request improves the README.md for vcluster by adding a table of contents, reorganizing sections, and enhancing the overall structure. It enhances the documentation and provides a more user-friendly experience.

**Please provide a short message that should be published in the vcluster release notes**
Improved README.md with a table of contents and restructured sections for enhanced user experience.

**What else do we need to know?** 

Please consider merging this PR as this PR will enhance the user-experience.

### CODE REVIEW

**Comment by adarsh-jha-dev** [comment]
I request any of the maintainers to please have a look at this PR and let me know if this can be merged

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev thanks for the PR! I'm not sure if we agree with those changes, will need more time to review that.

@FabianKramm , could you please let me know if this can be merged?

**Comment by adarsh-jha-dev** [comment]
> @adarsh-jha-dev thanks for the PR! I'm not sure if we agree with those changes, will need more time to review that.

@FabianKramm , is there any update on this?

**Comment by heiko-braun** [comment]
Hi @adarsh-jha-dev Thanks for the proposal, but we decided to keep the structure as is.

**Pull request closed without merging**
