### PR TITLE
Refactor pause/resume cmds into lifecycle pkg

### PR DESCRIPTION
**Pull request by TylerGillson**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind feature

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
Allows cluster-api-provider-vcluster to leverage vcluster's pause/resume functionality

**Please provide a short message that should be published in the vcluster release notes**
Refactored vcluster pause/resume functionality to make it easily consumable by the vcluster CAPI controller

Required by:
- https://github.com/loft-sh/cluster-api-provider-vcluster/pull/18

### CODE REVIEW

**Comment by FabianKramm** [comment]
@TylerGillson thanks a lot for the PR! Since the scope of this is conflicting with our commercial offering Loft, we first need to discuss this internally.

**Comment by TylerGillson** [comment]
> @TylerGillson thanks a lot for the PR! We first need to discuss this internally.

Hey @FabianKramm - any updates on this?

**Comment by FabianKramm** [comment]
Hey @TylerGillson ! Yes we can merge this as its mostly a refactor, I still need to review it though, sorry for the delay

**Review by matskiv — APPROVED** [review]
Looks good :+1:

**Comment by matskiv** [comment]
Hello @TylerGillson :wave: 
We are planning to bring some vcluster T-shirts to KubeCon Europe, and I want to set some aside for the contributors that will be present at the conference. Are you attending by any chance? :)

**Pull request merged**
