### PR TITLE
feat: coredns pod supports affinity and stain tolerance

### PR DESCRIPTION
**Pull request by mayooot**
I want to add tolerance and taint for coredns pod, I have verified it in the development environment but we are using v0.18.1 version of chart.

image
image

### CODE REVIEW

**Review by FabianKramm — CHANGES_REQUESTED** [review]
@mayooot thanks for creating this PR! Can you add the changes to https://github.com/loft-sh/vcluster/blob/main/config/config.go and then run the script `go run hack/schema/main.go` to generate the values.yaml and schema correctly? Also would be good if you can add a small helm unit test for your change, then I can merge it!

**Comment by mayooot** [comment]
> @mayooot thanks for creating this PR! Can you add the changes to https://github.com/loft-sh/vcluster/blob/main/config/config.go and then run the script `go run hack/schema/main.go` to generate the values.yaml and schema correctly? Also would be good if you can add a small helm unit test for your change, then I can merge it!

@FabianKramm ok, I'm done

**Comment by mayooot** [comment]
> @mayooot thanks for creating this PR! Can you add the changes to https://github.com/loft-sh/vcluster/blob/main/config/config.go and then run the script `go run hack/schema/main.go` to generate the values.yaml and schema correctly? Also would be good if you can add a small helm unit test for your change, then I can merge it!

@FabianKramm OK, I've updated [config.go](https://github.com/loft-sh/vcluster/pull/2107/commits/5fc15056ac150be71f7d4eed9270eb1277c0aa6d), and written a helm test case.

This is the first time I've written a helm unit test, and since there are no test examples for affinity and tolerations in project, there may be errors, look [coredns-configmap_test.yaml](https://github.com/loft-sh/vcluster/pull/2107/commits/b9509ee637205783918c6c815745be7da46ee743)

Another thing that confuses me is that after I modify config.go and run `go run hack/schema/main.go`, `values.schema.json` has been changed, but `values.yaml` does not.

**Comment by FabianKramm** [comment]
@mayooot thanks a lot! LGTM now, the only remaining issue is that you need to add your `values.yaml` changes to `config/values.yaml` as that will be used to generate `chart/values.yaml`.

**Comment by mayooot** [comment]
> @mayooot thanks a lot! LGTM now, the only remaining issue is that you need to add your `values.yaml` changes to `config/values.yaml` as that will be used to generate `chart/values.yaml`.

 @FabianKramm  ok, I'm done

**Review by FabianKramm — APPROVED** [review]
LGTM

**Pull request merged**
