### PR TITLE
docs: inject dark mode

### PR DESCRIPTION
**Pull request by hrittikhere**
**What issue type does this pull request address?** (keep at least one, remove the others) 

/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #

Adds the dark mode to the documentation. The provided code snippet describes a color mode configuration with three properties. The defaultMode is set to 'light', indicating that the default color mode is set to a light theme. The disableSwitch property is set to false, allowing users to switch between different color modes. The respectPrefersColorScheme property is set to true, which means the color mode will respect the user's preference specified in their operating system or browser settings. Overall, this configuration ensures that the default color mode is light, users can switch between color modes, and the color mode will adapt to the user's preferred color scheme if specified.

image

### CODE REVIEW

**Comment by hrittikhere** [comment]
@richburroughs felt this is important. What do you think?

**Comment by richburroughs** [comment]
Hey yes I think it's great to honor people's local settings for dark/light mode :)

**Comment by richburroughs** [comment]
Oh, @hrittikhere, I forgot to ask, were you able to test this? Or does that still need to get done?

**Comment by hrittikhere** [comment]
Hey @richburroughs 
It works mostly fine: https://0fa2-20-10-129-115.ngrok-free.app/docs/what-are-virtual-clusters

However, in this page and few in the `Full Guide` section there's a white gap: https://0fa2-20-10-129-115.ngrok-free.app/docs/getting-started/deployment

image

**Comment by hrittikhere** [comment]
Pulling down the server. I reccomend you test it locally once :)

**Comment by ishankhare07** [comment]
Hey @hrittikhere , thanks for this PR. We can consider merging this if you can fix the existing "white gap" issue that you pointed above.

**Comment by hrittikhere** [comment]
@ishankhare07 I was away on a vaccination, so I didn't get time to look into it. Thanks for the suggestion, and I have added the change, and it looks good. LMK what you think:

CC: @richburroughs 

image

**Review by ishankhare07 — APPROVED** [review]

**Comment by hrittikhere** [comment]
Hey @ishankhare07, I'm just wondering about the merge pipeline. Can you also let me know about the deployment process after the merge is complete?

**Review by ThomasK33 — CHANGES_REQUESTED** [review]
Hey @hrittikhere 👋 ,

I just tested your changes in Safari on macOS Venture 13.5, and the scroll bar is white + the "Join us on Slack" and GitHub buttons in the top bar do not adjust to the color scheme and are hard to see, as marked in the screenshot.

Screenshot 2023-08-08 at 13 52 17


Regarding the scroll bar, you might have to look into either [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar) or `color-scheme: light dark` (source: <https://github.com/ionic-team/ionic-framework/issues/20921#issuecomment-606767716> + <https://dev.to/okikio/psa-add-dark-mode-to-your-sites-or-at-least-let-the-browsers-do-it-for-you-18hi>)

---

If those two changes are in, this PR should be ready.

**Comment by ThomasK33** [comment]
> Can you also let me know about the deployment process after the merge is complete?

Once the docs get merged onto the main branch, [a GitHub action](https://github.com/loft-sh/vcluster/blob/main/.github/workflows/docs.yaml) is triggered, which builds the docs and then deploys the build output to Netlify, as that's where the docs are hosted.

**Comment by hrittikhere** [comment]
Thanks for the suggestion @ThomasK33 :) I have gone through them, and now they look good on my end. Do you mind testing and letting me know how do they look on your side? 



image

**Review by ThomasK33 — APPROVED** [review]
LGTM
Thanks for the quick fixes

**Comment by hrittikhere** [comment]
Welcome and thanks for the help 🙏

**Pull request merged**
